#' @export
box::use(
  app/logic/lda/data_splitting[
    create_stratified_split,
  ],
  app/logic/lda/ld_plot[
    create_ld_plot,
    ld_plot_error_parser,
    get_group_values,
    build_tooltips,
    ld_theme,
    axis_label,
  ],
  app/logic/lda/lda_diagnostics[
    compute_pooled_vc,
    generate_ellipse_points,
    add_diagnostics_overlay,
    add_boundaries_overlay,
    compute_1d_boundary,
  ],
  app/logic/lda/lda[
    lda_error_parser,
    run_lda,
    run_predict,
    run_qda,
    validate_inputs,
  ],
  app/logic/lda/lda_export[
    create_lda_excel,
  ],
)
